window.QUIET_BUG_EXERCISES = [
  {
    id: 1,
    title: "Find the Maximum Number in an Array",
    language: "Java",
    level: "Junior",
    pattern: "Loop, helper variable, comparison",
    prompt: "Write a Java method that receives an array of integers and returns the largest number.",
    exampleInput: "findMax(new int[]{3, 8, 2, 10, 5});",
    expectedOutput: "10",
    starterCode: "public static int findMax(int[] numbers) {\n    // Your code here\n}",
    hints: [
      "Start by identifying what the method receives and what it needs to return.",
      "Use a variable to remember the largest number found so far.",
      "Before using numbers[0], check if the array is null or empty."
    ],
    oralExplanation: "I'll start by checking if the array is null or empty. Then I'll assume the first element is the largest value. I'll loop through the rest of the array and update max when I find a larger number.",
    solution: "public static int findMax(int[] numbers) {\n    if (numbers == null || numbers.length == 0) {\n        throw new IllegalArgumentException(\"Array cannot be null or empty\");\n    }\n\n    int max = numbers[0];\n\n    for (int i = 1; i < numbers.length; i++) {\n        if (numbers[i] > max) {\n            max = numbers[i];\n        }\n    }\n\n    return max;\n}",
    feedback: ["Identify input and output before coding.", "Use a helper variable instead of guessing.", "Mention null and empty arrays as edge cases."],
    employerPerspective: "The interviewer is checking whether you can structure a simple loop, explain your reasoning and avoid silent guessing."
  },
  {
    id: 2,
    title: "Count Even Numbers",
    language: "Java",
    level: "Junior",
    pattern: "Loop, condition, counter",
    prompt: "Write a Java method that receives an array of integers and returns how many numbers are even.",
    exampleInput: "countEven(new int[]{2, 5, 8, 11, 14});",
    expectedOutput: "3",
    starterCode: "public static int countEven(int[] numbers) {\n    // Your code here\n}",
    hints: ["You need to inspect every number.", "Use a counter that starts at zero.", "A number is even when number % 2 == 0."],
    oralExplanation: "I'll loop through the array and use a counter. For each number, I'll check if it is divisible by two. If it is, I'll increase the counter and return it at the end.",
    solution: "public static int countEven(int[] numbers) {\n    if (numbers == null) {\n        return 0;\n    }\n\n    int count = 0;\n\n    for (int number : numbers) {\n        if (number % 2 == 0) {\n            count++;\n        }\n    }\n\n    return count;\n}",
    feedback: ["Use modulo clearly.", "Initialize the counter before the loop.", "Explain what happens with an empty array."],
    employerPerspective: "This exercise shows whether you can combine a loop, a condition and a small piece of state."
  },
  {
    id: 3,
    title: "Sum Positive Numbers",
    language: "Java",
    level: "Junior",
    pattern: "Loop, condition, accumulator",
    prompt: "Write a Java method that receives an array of integers and returns the sum of only the positive numbers.",
    exampleInput: "sumPositive(new int[]{3, -2, 7, 0, -5});",
    expectedOutput: "10",
    starterCode: "public static int sumPositive(int[] numbers) {\n    // Your code here\n}",
    hints: ["You need an accumulator variable.", "Only add numbers greater than zero.", "Zero is not positive."],
    oralExplanation: "I'll create a sum variable starting at zero. Then I'll loop through the numbers and only add values that are greater than zero.",
    solution: "public static int sumPositive(int[] numbers) {\n    if (numbers == null) {\n        return 0;\n    }\n\n    int sum = 0;\n\n    for (int number : numbers) {\n        if (number > 0) {\n            sum += number;\n        }\n    }\n\n    return sum;\n}",
    feedback: ["Separate the condition from the accumulation.", "Be clear that zero is ignored.", "Keep the return outside the loop."],
    employerPerspective: "The interviewer is looking for readable control flow and a calm explanation of a basic accumulator pattern."
  },
  {
    id: 4,
    title: "Check if an Array Contains a Number",
    language: "Java",
    level: "Junior",
    pattern: "Loop, boolean return, early return",
    prompt: "Write a Java method that receives an array of integers and a target number, then returns true if the target exists in the array.",
    exampleInput: "containsNumber(new int[]{4, 9, 12}, 9);",
    expectedOutput: "true",
    starterCode: "public static boolean containsNumber(int[] numbers, int target) {\n    // Your code here\n}",
    hints: ["Compare each number with the target.", "Return true as soon as you find a match.", "Return false after the loop finishes."],
    oralExplanation: "I'll scan the array one item at a time. If any number equals the target, I can return true immediately. If the loop finishes with no match, I'll return false.",
    solution: "public static boolean containsNumber(int[] numbers, int target) {\n    if (numbers == null) {\n        return false;\n    }\n\n    for (int number : numbers) {\n        if (number == target) {\n            return true;\n        }\n    }\n\n    return false;\n}",
    feedback: ["Use early return intentionally.", "Do not return false too early.", "Explain the no-match path."],
    employerPerspective: "This checks whether you understand search logic and can explain why early return is useful."
  },
  {
    id: 5,
    title: "Reverse a String",
    language: "Java",
    level: "Junior",
    pattern: "String traversal, loop, result builder",
    prompt: "Write a Java method that receives a string and returns the reversed version.",
    exampleInput: "reverse(\"code\");",
    expectedOutput: "edoc",
    starterCode: "public static String reverse(String text) {\n    // Your code here\n}",
    hints: ["Start from the last character.", "Move backwards through the string.", "Use StringBuilder for the result."],
    oralExplanation: "I'll handle null first, then build a new string by reading the original text from the last character to the first.",
    solution: "public static String reverse(String text) {\n    if (text == null) {\n        return null;\n    }\n\n    StringBuilder result = new StringBuilder();\n\n    for (int i = text.length() - 1; i >= 0; i--) {\n        result.append(text.charAt(i));\n    }\n\n    return result.toString();\n}",
    feedback: ["Watch the loop boundaries.", "Use charAt correctly.", "Mention empty string behavior."],
    employerPerspective: "This exercise shows attention to indexes and whether you can narrate loop direction without getting lost."
  },
  {
    id: 6,
    title: "Count Vowels in a String",
    language: "Java",
    level: "Junior",
    pattern: "String, charAt, condition, counter",
    prompt: "Write a Java method that receives a string and returns how many vowels it contains.",
    exampleInput: "countVowels(\"interview\");",
    expectedOutput: "4",
    starterCode: "public static int countVowels(String text) {\n    // Your code here\n}",
    hints: ["Loop through each character.", "Normalize the text to lowercase.", "Check whether the character is a, e, i, o or u."],
    oralExplanation: "I'll convert the string to lowercase so uppercase vowels are handled the same way. Then I'll loop through every character and count matches.",
    solution: "public static int countVowels(String text) {\n    if (text == null) {\n        return 0;\n    }\n\n    int count = 0;\n    String lowerText = text.toLowerCase();\n\n    for (int i = 0; i < lowerText.length(); i++) {\n        char letter = lowerText.charAt(i);\n\n        if (letter == 'a' || letter == 'e' || letter == 'i' || letter == 'o' || letter == 'u') {\n            count++;\n        }\n    }\n\n    return count;\n}",
    feedback: ["Handle uppercase input.", "Keep the vowel condition readable.", "Use a counter rather than returning inside the loop."],
    employerPerspective: "The interviewer is checking basic string traversal and whether you can make a condition understandable."
  },
  {
    id: 7,
    title: "Validate a Password",
    language: "Java",
    level: "Junior",
    pattern: "Conditions, boolean logic, validation",
    prompt: "Write a Java method that receives a password and returns true if it has at least 8 characters and contains at least one digit.",
    exampleInput: "isValidPassword(\"quiet123\");",
    expectedOutput: "true",
    starterCode: "public static boolean isValidPassword(String password) {\n    // Your code here\n}",
    hints: ["Check null before checking length.", "Use length for the minimum size rule.", "Loop through characters to find a digit."],
    oralExplanation: "I'll first reject null or short passwords. Then I'll scan the characters and return true when I find at least one digit.",
    solution: "public static boolean isValidPassword(String password) {\n    if (password == null || password.length() < 8) {\n        return false;\n    }\n\n    for (int i = 0; i < password.length(); i++) {\n        if (Character.isDigit(password.charAt(i))) {\n            return true;\n        }\n    }\n\n    return false;\n}",
    feedback: ["Validate the simplest rules first.", "Use Character.isDigit for clarity.", "Explain why false is returned at the end."],
    employerPerspective: "This checks whether you can translate written rules into clear boolean logic."
  },
  {
    id: 8,
    title: "Check if All Numbers Are Positive",
    language: "Java",
    level: "Junior",
    pattern: "Loop, condition, early return",
    prompt: "Write a Java method that returns true only if every number in the array is greater than zero.",
    exampleInput: "allPositive(new int[]{1, 3, 8});",
    expectedOutput: "true",
    starterCode: "public static boolean allPositive(int[] numbers) {\n    // Your code here\n}",
    hints: ["Look for the failure case.", "If any number is zero or negative, return false.", "Return true only after checking all numbers."],
    oralExplanation: "I'll loop through the numbers and look for anything that is not positive. If I find one, I can return false. If not, all numbers are positive.",
    solution: "public static boolean allPositive(int[] numbers) {\n    if (numbers == null || numbers.length == 0) {\n        return false;\n    }\n\n    for (int number : numbers) {\n        if (number <= 0) {\n            return false;\n        }\n    }\n\n    return true;\n}",
    feedback: ["Think about the negative path first.", "Treat zero as not positive.", "Return true after the loop, not inside it."],
    employerPerspective: "The interviewer is checking whether you understand all-item checks and careful boolean placement."
  },
  {
    id: 9,
    title: "Create a Student Class with isPassed",
    language: "Java",
    level: "Junior",
    pattern: "OOP, class, constructor, method",
    prompt: "Create a Student class with name and grade fields, a constructor, getters and an isPassed method that returns true when grade is at least 50.",
    exampleInput: "Student student = new Student(\"Ana\", 75);\nstudent.isPassed();",
    expectedOutput: "true",
    starterCode: "public class Student {\n    // attributes\n\n    // constructor\n\n    // getters\n\n    // isPassed method\n}",
    hints: ["Start with private attributes.", "Use the constructor to initialize name and grade.", "isPassed should return grade >= 50."],
    oralExplanation: "I'll model the student with private fields and a constructor. The isPassed method can use the grade field directly and return whether it meets the passing threshold.",
    solution: "public class Student {\n    private String name;\n    private int grade;\n\n    public Student(String name, int grade) {\n        this.name = name;\n        this.grade = grade;\n    }\n\n    public String getName() {\n        return name;\n    }\n\n    public int getGrade() {\n        return grade;\n    }\n\n    public boolean isPassed() {\n        return grade >= 50;\n    }\n}",
    feedback: ["Use private fields.", "Keep isPassed focused on one rule.", "Explain the threshold clearly."],
    employerPerspective: "This shows whether you can create a small class and connect object state to behavior."
  },
  {
    id: 10,
    title: "Create a BankAccount Class with Validation",
    language: "Java",
    level: "Junior",
    pattern: "OOP, encapsulation, validation, methods",
    prompt: "Create a BankAccount class with owner, balance, constructor, getters, deposit and withdraw methods. Validate owner, initial balance, deposits and withdrawals.",
    exampleInput: "BankAccount account = new BankAccount(\"Ana\", 100);\naccount.deposit(50);\naccount.withdraw(30);\naccount.getBalance();",
    expectedOutput: "120.0",
    starterCode: "public class BankAccount {\n    // attributes\n\n    // constructor\n\n    // getters\n\n    // deposit method\n\n    // withdraw method\n}",
    hints: ["Use private attributes to protect object state.", "Validate constructor inputs before assigning fields.", "Change balance only through deposit and withdraw."],
    oralExplanation: "I'll keep owner and balance private. The constructor will validate the initial values, and the balance will only change through deposit and withdraw because those methods enforce the rules.",
    solution: "public class BankAccount {\n    private String owner;\n    private double balance;\n\n    public BankAccount(String owner, double balance) {\n        if (owner == null || owner.isBlank()) {\n            throw new IllegalArgumentException(\"Owner cannot be null or empty\");\n        }\n\n        if (balance < 0) {\n            throw new IllegalArgumentException(\"Initial balance cannot be negative\");\n        }\n\n        this.owner = owner;\n        this.balance = balance;\n    }\n\n    public String getOwner() {\n        return owner;\n    }\n\n    public double getBalance() {\n        return balance;\n    }\n\n    public void deposit(double amount) {\n        if (amount <= 0) {\n            throw new IllegalArgumentException(\"Deposit amount must be greater than zero\");\n        }\n\n        balance += amount;\n    }\n\n    public void withdraw(double amount) {\n        if (amount <= 0 || amount > balance) {\n            throw new IllegalArgumentException(\"Invalid withdrawal amount\");\n        }\n\n        balance -= amount;\n    }\n}",
    feedback: ["Protect state with private fields.", "Avoid a direct balance setter.", "Explain validation as part of encapsulation."],
    employerPerspective: "This checks whether you understand basic OOP, validation and why controlled methods are safer than public fields."
  }
];
